/*
 MindLink — Painel Analítico-Preditivo de Demência no SUS
 Equipe She Leads
 Ana Júlia Amorim — RM 572387
 Beatriz Dias da Silva — RM 569873
 Luana Ramos Rabelo — RM 570351
 Mariana Ishikawa — RM 572886
 Sthefany Feitosa da Silva — RM 568651

 Datasets públicos:
 - SIH/SUS RD via PySUS: https://pysus.readthedocs.io/
 - Hospitais e Leitos/CNES: https://dadosabertos.saude.gov.br/dataset/hospitais-e-leitos
 - CID-10 DATASUS: https://www2.datasus.gov.br/cid10/V2008/descrcsv.htm

 Recorte experimental: Estado de São Paulo, competências 202401 a 202512.
 Critério clínico: CID principal iniciado por F00, F01, F02, F03 ou G30.
*/

-- DROP VIEW VW_CANDIDATOS_REALOCACAO;
-- DROP VIEW VW_PRESSAO_HOSPITALAR;
-- DROP TABLE PREVISAO_PRESSAO_TRIMESTRAL CASCADE CONSTRAINTS PURGE;
-- DROP TABLE FATO_COMORBIDADE_MENSAL CASCADE CONSTRAINTS PURGE;
-- DROP TABLE FATO_CAPACIDADE_MENSAL CASCADE CONSTRAINTS PURGE;
-- DROP TABLE FATO_INTERNACAO_MENSAL CASCADE CONSTRAINTS PURGE;
-- DROP TABLE DIM_FAIXA_ETARIA CASCADE CONSTRAINTS PURGE;
-- DROP TABLE DIM_DIAGNOSTICO CASCADE CONSTRAINTS PURGE;
-- DROP TABLE DIM_ESTABELECIMENTO CASCADE CONSTRAINTS PURGE;
-- DROP TABLE DIM_MUNICIPIO CASCADE CONSTRAINTS PURGE;
-- DROP TABLE DIM_TEMPO CASCADE CONSTRAINTS PURGE;
-- DROP TABLE STG_MINDLINK_COMORBIDADES PURGE;
-- DROP TABLE STG_MINDLINK_CAPACIDADE PURGE;
-- DROP TABLE STG_MINDLINK_INTERNACOES PURGE;

CREATE TABLE STG_MINDLINK_INTERNACOES (
    COMPETENCIA                 NUMBER(6)       NOT NULL,
    CODIGO_IBGE                 VARCHAR2(6)     NOT NULL,
    MUNICIPIO_ATENDIMENTO       VARCHAR2(120)   NOT NULL,
    CNES                        VARCHAR2(7)     NOT NULL,
    NOME_ESTABELECIMENTO        VARCHAR2(255)   NOT NULL,
    CID_PRINCIPAL               VARCHAR2(7)     NOT NULL,
    DESCRICAO_CID_PRINCIPAL     VARCHAR2(500)   NOT NULL,
    FAIXA_ETARIA                VARCHAR2(20)    NOT NULL,
    SEXO_DESC                   VARCHAR2(20)    NOT NULL,
    QTD_INTERNACOES             NUMBER(10)      NOT NULL,
    DIAS_PERMANENCIA            NUMBER(12)      NOT NULL,
    VALOR_TOTAL                 NUMBER(16,2)    NOT NULL,
    QTD_OBITOS                  NUMBER(10)      NOT NULL
);

CREATE TABLE STG_MINDLINK_COMORBIDADES (
    COMPETENCIA                         NUMBER(6)      NOT NULL,
    CODIGO_IBGE                         VARCHAR2(6)    NOT NULL,
    CNES                                VARCHAR2(7)    NOT NULL,
    CID_PRINCIPAL                       VARCHAR2(7)    NOT NULL,
    CID_SECUNDARIO                      VARCHAR2(7)    NOT NULL,
    QTD_INTERNACOES_COM_COMORBIDADE     NUMBER(10)     NOT NULL,
    DESCRICAO_CID_SECUNDARIO            VARCHAR2(500)  NOT NULL
);

CREATE TABLE STG_MINDLINK_CAPACIDADE (
    COMPETENCIA                 NUMBER(6)      NOT NULL,
    CODIGO_IBGE                 VARCHAR2(6)    NOT NULL,
    MUNICIPIO_ATENDIMENTO       VARCHAR2(120)  NOT NULL,
    CNES                        VARCHAR2(7)    NOT NULL,
    NOME_ESTABELECIMENTO        VARCHAR2(255)  NOT NULL,
    DS_TIPO_UNIDADE             VARCHAR2(120)  NOT NULL,
    TP_GESTAO                   VARCHAR2(10)   NOT NULL,
    LEITOS_EXISTENTES           NUMBER(10)     NOT NULL,
    LEITOS_SUS                  NUMBER(10)     NOT NULL,
    UTI_TOTAL_EXIST             NUMBER(10)     NOT NULL,
    UTI_TOTAL_SUS               NUMBER(10)     NOT NULL
);

CREATE TABLE DIM_TEMPO (
    ID_TEMPO       NUMBER(6)      PRIMARY KEY,
    ANO            NUMBER(4)      NOT NULL,
    MES            NUMBER(2)      NOT NULL,
    TRIMESTRE      NUMBER(1)      NOT NULL,
    DATA_INICIO    DATE           NOT NULL,
    CONSTRAINT CK_DIM_TEMPO_MES CHECK (MES BETWEEN 1 AND 12)
);

CREATE TABLE DIM_MUNICIPIO (
    CODIGO_IBGE       VARCHAR2(6)    PRIMARY KEY,
    NOME_MUNICIPIO    VARCHAR2(120)  NOT NULL,
    UF                CHAR(2)        DEFAULT 'SP' NOT NULL
);

CREATE TABLE DIM_ESTABELECIMENTO (
    CNES                    VARCHAR2(7)    PRIMARY KEY,
    NOME_ESTABELECIMENTO     VARCHAR2(255)  NOT NULL,
    CODIGO_IBGE              VARCHAR2(6)    NOT NULL,
    TIPO_UNIDADE             VARCHAR2(120),
    TIPO_GESTAO              VARCHAR2(10),
    CONSTRAINT FK_ESTAB_MUNICIPIO FOREIGN KEY (CODIGO_IBGE)
        REFERENCES DIM_MUNICIPIO (CODIGO_IBGE)
);

CREATE TABLE DIM_DIAGNOSTICO (
    CODIGO_CID          VARCHAR2(7)    PRIMARY KEY,
    DESCRICAO_CID       VARCHAR2(500)  NOT NULL,
    TIPO_DIAGNOSTICO    VARCHAR2(30)   NOT NULL,
    CONSTRAINT CK_TIPO_DIAGNOSTICO CHECK (
        TIPO_DIAGNOSTICO IN ('DEMENCIA_PRINCIPAL', 'DIAGNOSTICO_SECUNDARIO')
    )
);

CREATE TABLE DIM_FAIXA_ETARIA (
    CODIGO_FAIXA     VARCHAR2(20)  PRIMARY KEY,
    DESCRICAO_FAIXA  VARCHAR2(80)  NOT NULL,
    IDADE_MINIMA     NUMBER(3),
    IDADE_MAXIMA     NUMBER(3)
);

CREATE TABLE FATO_INTERNACAO_MENSAL (
    ID_FATO                 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TEMPO                NUMBER(6)      NOT NULL,
    CODIGO_IBGE             VARCHAR2(6)    NOT NULL,
    CNES                    VARCHAR2(7)    NOT NULL,
    CID_PRINCIPAL           VARCHAR2(7)    NOT NULL,
    CODIGO_FAIXA            VARCHAR2(20)   NOT NULL,
    SEXO                    VARCHAR2(20)   NOT NULL,
    QTD_INTERNACOES         NUMBER(10)     NOT NULL,
    DIAS_PERMANENCIA        NUMBER(12)     NOT NULL,
    VALOR_TOTAL             NUMBER(16,2)   NOT NULL,
    QTD_OBITOS              NUMBER(10)     NOT NULL,
    CONSTRAINT FK_INT_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO),
    CONSTRAINT FK_INT_MUNICIPIO FOREIGN KEY (CODIGO_IBGE) REFERENCES DIM_MUNICIPIO (CODIGO_IBGE),
    CONSTRAINT FK_INT_ESTAB FOREIGN KEY (CNES) REFERENCES DIM_ESTABELECIMENTO (CNES),
    CONSTRAINT FK_INT_CID FOREIGN KEY (CID_PRINCIPAL) REFERENCES DIM_DIAGNOSTICO (CODIGO_CID),
    CONSTRAINT FK_INT_FAIXA FOREIGN KEY (CODIGO_FAIXA) REFERENCES DIM_FAIXA_ETARIA (CODIGO_FAIXA),
    CONSTRAINT UK_INT_GRAO UNIQUE (ID_TEMPO, CNES, CID_PRINCIPAL, CODIGO_FAIXA, SEXO)
);

CREATE TABLE FATO_COMORBIDADE_MENSAL (
    ID_COMORBIDADE                    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TEMPO                          NUMBER(6)     NOT NULL,
    CODIGO_IBGE                       VARCHAR2(6)   NOT NULL,
    CNES                              VARCHAR2(7)   NOT NULL,
    CID_PRINCIPAL                     VARCHAR2(7)   NOT NULL,
    CID_SECUNDARIO                    VARCHAR2(7)   NOT NULL,
    QTD_INTERNACOES_COM_COMORBIDADE   NUMBER(10)    NOT NULL,
    CONSTRAINT FK_COM_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO),
    CONSTRAINT FK_COM_MUNICIPIO FOREIGN KEY (CODIGO_IBGE) REFERENCES DIM_MUNICIPIO (CODIGO_IBGE),
    CONSTRAINT FK_COM_ESTAB FOREIGN KEY (CNES) REFERENCES DIM_ESTABELECIMENTO (CNES),
    CONSTRAINT FK_COM_CID_PRINC FOREIGN KEY (CID_PRINCIPAL) REFERENCES DIM_DIAGNOSTICO (CODIGO_CID),
    CONSTRAINT FK_COM_CID_SEC FOREIGN KEY (CID_SECUNDARIO) REFERENCES DIM_DIAGNOSTICO (CODIGO_CID),
    CONSTRAINT UK_COM_GRAO UNIQUE (ID_TEMPO, CNES, CID_PRINCIPAL, CID_SECUNDARIO)
);

CREATE TABLE FATO_CAPACIDADE_MENSAL (
    ID_CAPACIDADE          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TEMPO               NUMBER(6)    NOT NULL,
    CODIGO_IBGE            VARCHAR2(6)  NOT NULL,
    CNES                   VARCHAR2(7)  NOT NULL,
    LEITOS_EXISTENTES      NUMBER(10)   NOT NULL,
    LEITOS_SUS             NUMBER(10)   NOT NULL,
    UTI_TOTAL_EXIST        NUMBER(10)   NOT NULL,
    UTI_TOTAL_SUS          NUMBER(10)   NOT NULL,
    CONSTRAINT FK_CAP_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO),
    CONSTRAINT FK_CAP_MUNICIPIO FOREIGN KEY (CODIGO_IBGE) REFERENCES DIM_MUNICIPIO (CODIGO_IBGE),
    CONSTRAINT FK_CAP_ESTAB FOREIGN KEY (CNES) REFERENCES DIM_ESTABELECIMENTO (CNES),
    CONSTRAINT UK_CAP_GRAO UNIQUE (ID_TEMPO, CNES)
);

CREATE TABLE PREVISAO_PRESSAO_TRIMESTRAL (
    ID_PREVISAO                   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_GERACAO                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ID_TEMPO_PREVISTO             NUMBER(6)     NOT NULL,
    CNES                          VARCHAR2(7)   NOT NULL,
    HORIZONTE_MESES               NUMBER(1)     NOT NULL,
    DIAS_PERMANENCIA_PREVISTOS    NUMBER(14,2)  NOT NULL,
    PRESSAO_PREVISTA_PCT          NUMBER(9,4)   NOT NULL,
    LIMITE_INFERIOR               NUMBER(14,2),
    LIMITE_SUPERIOR               NUMBER(14,2),
    NIVEL_RISCO                   VARCHAR2(15)  NOT NULL,
    MODELO                        VARCHAR2(80)  NOT NULL,
    CONSTRAINT FK_PREV_TEMPO FOREIGN KEY (ID_TEMPO_PREVISTO) REFERENCES DIM_TEMPO (ID_TEMPO),
    CONSTRAINT FK_PREV_ESTAB FOREIGN KEY (CNES) REFERENCES DIM_ESTABELECIMENTO (CNES),
    CONSTRAINT CK_PREV_HORIZONTE CHECK (HORIZONTE_MESES BETWEEN 1 AND 3),
    CONSTRAINT CK_PREV_RISCO CHECK (NIVEL_RISCO IN ('BAIXO', 'ATENCAO', 'CRITICO'))
);

CREATE INDEX IX_INT_TEMPO_MUNICIPIO ON FATO_INTERNACAO_MENSAL (ID_TEMPO, CODIGO_IBGE);
CREATE INDEX IX_INT_ESTAB_CID ON FATO_INTERNACAO_MENSAL (CNES, CID_PRINCIPAL);
CREATE INDEX IX_COM_CID_SEC ON FATO_COMORBIDADE_MENSAL (CID_SECUNDARIO);
CREATE INDEX IX_CAP_TEMPO_MUNICIPIO ON FATO_CAPACIDADE_MENSAL (ID_TEMPO, CODIGO_IBGE);

CREATE OR REPLACE VIEW VW_PRESSAO_HOSPITALAR AS
SELECT
    f.ID_TEMPO,
    f.CODIGO_IBGE,
    m.NOME_MUNICIPIO,
    f.CNES,
    e.NOME_ESTABELECIMENTO,
    MAX(c.LEITOS_SUS) AS LEITOS_SUS,
    SUM(f.QTD_INTERNACOES) AS QTD_INTERNACOES_DEMENCIA,
    SUM(f.DIAS_PERMANENCIA) AS DIAS_PERMANENCIA_DEMENCIA,
    ROUND(
        100 * SUM(f.DIAS_PERMANENCIA)
        / NULLIF(MAX(c.LEITOS_SUS) * EXTRACT(DAY FROM LAST_DAY(t.DATA_INICIO)), 0),
        4
    ) AS PRESSAO_DEMENCIA_PCT,
    MAX(c.LEITOS_SUS) * EXTRACT(DAY FROM LAST_DAY(t.DATA_INICIO))
        - SUM(f.DIAS_PERMANENCIA) AS SALDO_LEITOS_DIA_PROXY
FROM FATO_INTERNACAO_MENSAL f
JOIN DIM_TEMPO t ON t.ID_TEMPO = f.ID_TEMPO
JOIN DIM_MUNICIPIO m ON m.CODIGO_IBGE = f.CODIGO_IBGE
JOIN DIM_ESTABELECIMENTO e ON e.CNES = f.CNES
LEFT JOIN FATO_CAPACIDADE_MENSAL c
    ON c.ID_TEMPO = f.ID_TEMPO AND c.CNES = f.CNES
GROUP BY
    f.ID_TEMPO, f.CODIGO_IBGE, m.NOME_MUNICIPIO,
    f.CNES, e.NOME_ESTABELECIMENTO, t.DATA_INICIO;

CREATE OR REPLACE VIEW VW_CANDIDATOS_REALOCACAO AS
SELECT
    p.*,
    DENSE_RANK() OVER (
        PARTITION BY p.ID_TEMPO
        ORDER BY p.PRESSAO_DEMENCIA_PCT ASC NULLS LAST,
                 p.SALDO_LEITOS_DIA_PROXY DESC
    ) AS RANK_CAPACIDADE_RELATIVA
FROM VW_PRESSAO_HOSPITALAR p
WHERE p.LEITOS_SUS > 0;

COMMENT ON TABLE VW_PRESSAO_HOSPITALAR IS
'Proxy experimental: dias de permanencia por demencia divididos pelos leitos-dia SUS cadastrados. Nao representa ocupacao hospitalar total ou disponibilidade em tempo real.';
